name: Sync Image to Aliyun  Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ali_bill
        password: bill1234
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         # skopeo copy docker://docker.io/hslr/sun-panel:1.4.0 docker://registry.cn-hangzhou.aliyuncs.com/alibill/sun-panel:1.4.0
         skopeo copy docker://docker.io/hectorqin/reader:latest docker://registry.cn-hangzhou.aliyuncs.com/alibill/reader:latest
         skopeo copy docker://docker.io/python:3.10 docker://registry.cn-hangzhou.aliyuncs.com/alibill/python:3.10
         skopeo copy docker://docker.io/ubuntu:22.04 docker://registry.cn-hangzhou.aliyuncs.com/alibill/ubuntu:22.04
         skopeo copy docker://docker.io/mysql:8.0 docker://registry.cn-hangzhou.aliyuncs.com/alibill/mysql:8.0
         skopeo copy docker://docker.io/postgres:latest docker://registry.cn-hangzhou.aliyuncs.com/alibill/postgres:latest
         skopeo copy docker://docker.io/tdengine/tdengine:latest docker://registry.cn-hangzhou.aliyuncs.com/alibill/tdengine:latest
         skopeo copy docker://docker.io/tdengine/tdengine:3.2.3.0 docker://registry.cn-hangzhou.aliyuncs.com/alibill/tdengine:3.2.3.0
         skopeo copy docker://docker.io/apache/activemq-artemis:latest-alpine docker://registry.cn-hangzhou.aliyuncs.com/alibill/activemq-artemis:latest-alpine
      # 使用 skopeo 工具将镜像同步到阿里云个人仓库中，使用时请自行源和目标修改仓库名称和镜像名称
